### PR TITLE
Chiper: Track gapps repo

### PR DESCRIPTION
**Pull request by TejasKamat**

### CODE REVIEW

**Comment by tattwamashi** [comment]
@DrTK001 Not sure what is "Chiper"
And tracking from which gitlab... Noice pr..

**Comment by techyminati** [comment]
@DrTK001 1.) We dont know what's "Chiper"
2.)gitlab.com/cipheros/android_vendor_gms doesnt exist

**Comment by TejasKamat** [comment]
> @DrTK001 1.) We dont know what's "Chiper" 2.)gitlab.com/cipheros/android_vendor_gms doesnt exist

Typo mistake its cipher

**Comment by tattwamashi** [comment]
@DrTK001 Then tell us where is the gms repo bruuuuh

**Comment by DEVJAYDEEP** [comment]
@DrTK001 repo doesn't exist

**Comment by wileylau** [comment]
> @DrTK001 repo doesn't exist

The PR itself is closed. Dont reply to dead PRs.

**Pull request closed without merging**
